processed 18 tasks

task 5 'run'. lines 13-21:
{
  "gas_used": 491764,
  "status": {
    "Keep": "Executed"
  }
}

task 8 'run'. lines 132-141:
{
  "gas_used": 1091610,
  "status": {
    "Keep": "Executed"
  }
}

task 9 'run'. lines 145-159:
{
  "gas_used": 0,
  "status": {
    "Discard": 506
  }
}

task 10 'run'. lines 161-186:
{
  "gas_used": 306386,
  "status": {
    "Keep": "Executed"
  }
}

task 11 'run'. lines 188-204:
{
  "gas_used": 214125,
  "status": {
    "Keep": "Executed"
  }
}

task 12 'run'. lines 206-222:
{
  "gas_used": 214125,
  "status": {
    "Keep": "Executed"
  }
}

task 13 'run'. lines 225-246:
{
  "gas_used": 366904,
  "status": {
    "Keep": "Executed"
  }
}

task 15 'run'. lines 250-296:
{
  "gas_used": 103439,
  "status": {
    "Keep": {
      "MoveAbort": [
        {
          "Module": {
            "address": "0x00000000000000000000000000000001",
            "name": "GenesisDao"
          }
        },
        372487
      ]
    }
  }
}

task 17 'run'. lines 301-313:
{
  "gas_used": 106802,
  "status": {
    "Keep": {
      "MoveAbort": [
        {
          "Module": {
            "address": "0x00000000000000000000000000000001",
            "name": "GenesisDao"
          }
        },
        361729
      ]
    }
  }
}
