processed 19 tasks

task 5 'run'. lines 13-21:
{
  "gas_used": 491764,
  "status": {
    "Keep": "Executed"
  }
}

task 8 'run'. lines 132-141:
{
  "gas_used": 1091610,
  "status": {
    "Keep": "Executed"
  }
}

task 9 'run'. lines 143-157:
{
  "gas_used": 0,
  "status": {
    "Discard": 506
  }
}

task 10 'run'. lines 160-176:
{
  "gas_used": 214125,
  "status": {
    "Keep": "Executed"
  }
}

task 11 'run'. lines 178-194:
{
  "gas_used": 214125,
  "status": {
    "Keep": "Executed"
  }
}

task 12 'run'. lines 197-216:
{
  "gas_used": 366904,
  "status": {
    "Keep": "Executed"
  }
}

task 14 'run'. lines 220-234:
{
  "gas_used": 103439,
  "status": {
    "Keep": {
      "MoveAbort": [
        {
          "Module": {
            "address": "0x00000000000000000000000000000001",
            "name": "GenesisDao"
          }
        },
        372487
      ]
    }
  }
}

task 15 'run'. lines 236-250:
{
  "gas_used": 103439,
  "status": {
    "Keep": {
      "MoveAbort": [
        {
          "Module": {
            "address": "0x00000000000000000000000000000001",
            "name": "GenesisDao"
          }
        },
        372487
      ]
    }
  }
}

task 16 'run'. lines 252-266:
{
  "gas_used": 95619,
  "status": {
    "Keep": {
      "MoveAbort": [
        {
          "Module": {
            "address": "0x00000000000000000000000000000001",
            "name": "GenesisDao"
          }
        },
        367620
      ]
    }
  }
}

task 18 'run'. lines 271-283:
{
  "gas_used": 106802,
  "status": {
    "Keep": {
      "MoveAbort": [
        {
          "Module": {
            "address": "0x00000000000000000000000000000001",
            "name": "GenesisDao"
          }
        },
        361729
      ]
    }
  }
}
