processed 9 tasks

task 3 'run'. lines 7-19:
{
  "gas_used": 25350,
  "status": {
    "MoveAbort": {
      "location": {
        "Module": {
          "address": "0x00000000000000000000000000000001",
          "name": "CoreAddresses"
        }
      },
      "abort_code": "2818"
    }
  }
}

task 4 'run'. lines 22-34:
{
  "gas_used": 56979,
  "status": "Executed"
}

task 5 'run'. lines 37-51:
{
  "gas_used": 69422,
  "status": "Executed"
}

task 6 'run'. lines 54-67:
{
  "gas_used": 52637,
  "status": {
    "MoveAbort": {
      "location": {
        "Module": {
          "address": "0x00000000000000000000000000000001",
          "name": "Epoch"
        }
      },
      "abort_code": "19"
    }
  }
}

task 7 'run'. lines 70-83:
{
  "gas_used": 183411,
  "status": "Executed"
}

task 8 'run'. lines 86-99:
{
  "gas_used": 69418,
  "status": "Executed"
}
