processed 16 tasks

task 4 'run'. lines 46-54:
{
  "gas_used": 45401,
  "status": {
    "ExecutionFailure": {
      "location": {
        "Module": {
          "address": "0x00000000000000000000000000000001",
          "name": "DAOExtensionPoint"
        }
      },
      "function": 9,
      "code_offset": 22
    }
  }
}

task 5 'view'. lines 56-56:
[No Resource Exists]

task 6 'view'. lines 58-58:
[No Resource Exists]

task 7 'run'. lines 60-68:
{
  "gas_used": 33107,
  "status": {
    "ExecutionFailure": {
      "location": {
        "Module": {
          "address": "0x00000000000000000000000000000001",
          "name": "DAOExtensionPoint"
        }
      },
      "function": 8,
      "code_offset": 13
    }
  }
}

task 8 'view'. lines 70-70:
[No Resource Exists]

task 9 'view'. lines 72-72:
[No Resource Exists]

task 10 'run'. lines 74-82:
{
  "gas_used": 33109,
  "status": {
    "ExecutionFailure": {
      "location": {
        "Module": {
          "address": "0x00000000000000000000000000000001",
          "name": "DAOExtensionPoint"
        }
      },
      "function": 8,
      "code_offset": 13
    }
  }
}

task 11 'view'. lines 84-84:
[No Resource Exists]

task 12 'view'. lines 86-86:
[No Resource Exists]

task 13 'run'. lines 88-96:
{
  "gas_used": 33109,
  "status": {
    "ExecutionFailure": {
      "location": {
        "Module": {
          "address": "0x00000000000000000000000000000001",
          "name": "DAOExtensionPoint"
        }
      },
      "function": 8,
      "code_offset": 13
    }
  }
}

task 14 'view'. lines 98-98:
[No Resource Exists]

task 15 'view'. lines 100-100:
[No Resource Exists]
