processed 17 tasks

task 8 'run'. lines 104-115:
{
  "gas_used": 1679130,
  "status": "Executed"
}

task 9 'run'. lines 117-136:
{
  "gas_used": 445521,
  "status": "Executed"
}

task 10 'run'. lines 138-170:
{
  "gas_used": 666211,
  "status": "Executed"
}

task 12 'run'. lines 174-186:
{
  "gas_used": 52853,
  "status": {
    "MoveAbort": {
      "location": {
        "Module": {
          "address": "0x00000000000000000000000000000001",
          "name": "DAOSpace"
        }
      },
      "abort_code": "77319"
    }
  }
}

task 13 'run'. lines 188-208:
{
  "gas_used": 253287,
  "status": "Executed"
}

task 15 'run'. lines 212-232:
{
  "gas_used": 240921,
  "status": "Executed"
}

task 16 'run'. lines 234-248:
{
  "gas_used": 362869,
  "status": "Executed"
}
