processed 17 tasks

task 8 'run'. lines 107-118:
{
  "gas_used": 1645442,
  "status": "Executed"
}

task 9 'run'. lines 120-139:
{
  "gas_used": 427915,
  "status": "Executed"
}

task 10 'run'. lines 141-173:
{
  "gas_used": 630999,
  "status": "Executed"
}

task 12 'run'. lines 177-189:
{
  "gas_used": 52853,
  "status": {
    "MoveAbort": {
      "location": {
        "Module": {
          "address": "0x00000000000000000000000000000001",
          "name": "DAOSpace"
        }
      },
      "abort_code": "77319"
    }
  }
}

task 13 'run'. lines 191-211:
{
  "gas_used": 253287,
  "status": "Executed"
}

task 15 'run'. lines 215-235:
{
  "gas_used": 240921,
  "status": "Executed"
}

task 16 'run'. lines 237-251:
{
  "gas_used": 345263,
  "status": "Executed"
}
