processed 13 tasks

task 6 'run'. lines 29-37:
{
  "gas_used": 149256,
  "status": "Executed"
}

task 7 'run'. lines 39-47:
{
  "gas_used": 206625,
  "status": "Executed"
}

task 8 'run'. lines 49-57:
{
  "gas_used": 16186,
  "status": {
    "MoveAbort": {
      "location": {
        "Module": {
          "address": "0x00000000000000000000000000000001",
          "name": "DAOPluginMarketplace"
        }
      },
      "abort_code": "26630"
    }
  }
}

task 9 'run'. lines 59-67:
{
  "gas_used": 16186,
  "status": {
    "MoveAbort": {
      "location": {
        "Module": {
          "address": "0x00000000000000000000000000000001",
          "name": "DAOPluginMarketplace"
        }
      },
      "abort_code": "26630"
    }
  }
}

task 11 'run'. lines 88-96:
{
  "gas_used": 206660,
  "status": "Executed"
}

task 12 'run'. lines 98-106:
{
  "gas_used": 16188,
  "status": {
    "MoveAbort": {
      "location": {
        "Module": {
          "address": "0x00000000000000000000000000000001",
          "name": "DAOPluginMarketplace"
        }
      },
      "abort_code": "26630"
    }
  }
}
