processed 17 tasks

task 4 'run'. lines 98-106:
{
  "gas_used": 329658,
  "status": "Executed"
}

task 8 'run'. lines 122-129:
{
  "gas_used": 600,
  "status": "MiscellaneousError"
}

task 9 'run'. lines 131-145:
{
  "gas_used": 200239,
  "status": "Executed"
}

task 10 'run'. lines 146-155:
{
  "gas_used": 1121690,
  "status": "Executed"
}

task 11 'deploy'. lines 157-157:
Publish failure: Discard { status_code: StrView(2015), status_code_name: "UNEXPECTED_ERROR_FROM_KNOWN_MOVE_FUNCTION" }

task 13 'run'. lines 161-168:
{
  "gas_used": 123208,
  "status": "Executed"
}

task 16 'run'. lines 174-181:
{
  "gas_used": 11344,
  "status": "Executed"
}
