processed 40 tasks

task 7 'run'. lines 126-135:
{
  "gas_used": 1168754,
  "status": {
    "MoveAbort": {
      "location": {
        "Module": {
          "address": "0x00000000000000000000000000000001",
          "name": "DAOSpace"
        }
      },
      "abort_code": "179201"
    }
  }
}

task 8 'run'. lines 139-153:
{
  "gas_used": 5286,
  "status": {
    "ExecutionFailure": {
      "location": {
        "Module": {
          "address": "0x00000000000000000000000000000001",
          "name": "DAORegistry"
        }
      },
      "function": 0,
      "code_offset": 1
    }
  }
}

task 9 'run'. lines 155-180:
{
  "gas_used": 306386,
  "status": "Executed"
}

task 11 'run'. lines 185-201:
{
  "gas_used": 42286,
  "status": {
    "ExecutionFailure": {
      "location": {
        "Module": {
          "address": "0x00000000000000000000000000000001",
          "name": "DAORegistry"
        }
      },
      "function": 0,
      "code_offset": 1
    }
  }
}

task 12 'run'. lines 203-219:
{
  "gas_used": 42286,
  "status": {
    "ExecutionFailure": {
      "location": {
        "Module": {
          "address": "0x00000000000000000000000000000001",
          "name": "DAORegistry"
        }
      },
      "function": 0,
      "code_offset": 1
    }
  }
}

task 16 'run'. lines 227-241:
{
  "gas_used": 104944,
  "status": "Executed"
}

task 19 'run'. lines 248-261:
{
  "gas_used": 532278,
  "status": {
    "MoveAbort": {
      "location": {
        "Module": {
          "address": "0x00000000000000000000000000000001",
          "name": "Block"
        }
      },
      "abort_code": "4609"
    }
  }
}

task 22 'run'. lines 268-279:
{
  "gas_used": 577624,
  "status": "Executed"
}

task 23 'run'. lines 282-306:
{
  "gas_used": 18867,
  "status": {
    "ExecutionFailure": {
      "location": {
        "Module": {
          "address": "0x00000000000000000000000000000001",
          "name": "DAORegistry"
        }
      },
      "function": 0,
      "code_offset": 1
    }
  }
}

task 25 'run'. lines 310-319:
{
  "gas_used": 11943,
  "status": "Executed"
}

task 26 'call'. lines 321-321:
"0xb5d577dc9ce59725e29886632e69ecdf/1/0x00000000000000000000000000000001::IdentifierNFT::IdentifierNFT<0x00000000000000000000000000000001::DAOSpace::DAOMember<0x662ba5a1a1da0f1c70a9762c7eeb7aaf::DAOHelper::X>,0x00000000000000000000000000000001::DAOSpace::DAOMemberBody<0x662ba5a1a1da0f1c70a9762c7eeb7aaf::DAOHelper::X>>"

task 28 'run'. lines 325-344:
{
  "gas_used": 3733,
  "status": {
    "ExecutionFailure": {
      "location": {
        "Module": {
          "address": "0x662ba5a1a1da0f1c70a9762c7eeb7aaf",
          "name": "DAOHelper"
        }
      },
      "function": 3,
      "code_offset": 1
    }
  }
}

task 29 'call'. lines 347-347:
"0xa7dcef9aef26202fce82a7c7d6672afb/1/0x00000000000000000000000000000001::IdentifierNFT::IdentifierNFT<0x00000000000000000000000000000001::DAOSpace::DAOMember<0x662ba5a1a1da0f1c70a9762c7eeb7aaf::DAOHelper::X>,0x00000000000000000000000000000001::DAOSpace::DAOMemberBody<0x662ba5a1a1da0f1c70a9762c7eeb7aaf::DAOHelper::X>>"

task 31 'run'. lines 351-364:
{
  "gas_used": 3205,
  "status": {
    "ExecutionFailure": {
      "location": {
        "Module": {
          "address": "0x662ba5a1a1da0f1c70a9762c7eeb7aaf",
          "name": "DAOHelper"
        }
      },
      "function": 3,
      "code_offset": 1
    }
  }
}

task 32 'call'. lines 367-367:
"0x3d4926eeda5b14b0ac979269ee79e40e/1/0x00000000000000000000000000000001::IdentifierNFT::IdentifierNFT<0x00000000000000000000000000000001::DAOSpace::DAOMember<0x662ba5a1a1da0f1c70a9762c7eeb7aaf::DAOHelper::X>,0x00000000000000000000000000000001::DAOSpace::DAOMemberBody<0x662ba5a1a1da0f1c70a9762c7eeb7aaf::DAOHelper::X>>"

task 34 'run'. lines 371-384:
{
  "gas_used": 3469,
  "status": {
    "ExecutionFailure": {
      "location": {
        "Module": {
          "address": "0x662ba5a1a1da0f1c70a9762c7eeb7aaf",
          "name": "DAOHelper"
        }
      },
      "function": 3,
      "code_offset": 1
    }
  }
}

task 36 'run'. lines 389-404:
{
  "gas_used": 2381,
  "status": {
    "ExecutionFailure": {
      "location": {
        "Module": {
          "address": "0x662ba5a1a1da0f1c70a9762c7eeb7aaf",
          "name": "DAOHelper"
        }
      },
      "function": 3,
      "code_offset": 1
    }
  }
}

task 39 'run'. lines 412-428:
{
  "gas_used": 17640,
  "status": {
    "ExecutionFailure": {
      "location": {
        "Module": {
          "address": "0x00000000000000000000000000000001",
          "name": "DAORegistry"
        }
      },
      "function": 0,
      "code_offset": 1
    }
  }
}
