processed 17 tasks

task 6 'run'. lines 32-40:
{
  "gas_used": 45401,
  "status": {
    "ExecutionFailure": {
      "location": {
        "Module": {
          "address": "0x00000000000000000000000000000001",
          "name": "DAOExtensionPoint"
        }
      },
      "function": 9,
      "code_offset": 22
    }
  }
}

task 7 'run'. lines 42-61:
{
  "gas_used": 42895,
  "status": {
    "ExecutionFailure": {
      "location": {
        "Module": {
          "address": "0x00000000000000000000000000000001",
          "name": "DAOExtensionPoint"
        }
      },
      "function": 12,
      "code_offset": 10
    }
  }
}

task 8 'run'. lines 63-72:
{
  "gas_used": 80067,
  "status": "Executed"
}

task 9 'view'. lines 74-74:
[No Resource Exists]

task 10 'run'. lines 76-85:
{
  "gas_used": 51453,
  "status": {
    "MoveAbort": {
      "location": {
        "Module": {
          "address": "0x00000000000000000000000000000001",
          "name": "NFTGallery"
        }
      },
      "abort_code": "25861"
    }
  }
}

task 11 'view'. lines 87-87:
[No Resource Exists]

task 12 'view'. lines 89-89:
store key 0x00000000000000000000000000000001::NFTGallery::NFTGallery<0x00000000000000000000000000000001::DAOExtensionPoint::OwnerNFTMeta, 0x00000000000000000000000000000001::DAOExtensionPoint::OwnerNFTBody> {
    withdraw_events: store 0x00000000000000000000000000000001::Event::EventHandle<0x00000000000000000000000000000001::NFTGallery::WithdrawEvent<0x00000000000000000000000000000001::DAOExtensionPoint::OwnerNFTMeta>> {
        counter: 0
        guid: 0300000000000000a7dcef9aef26202fce82a7c7d6672afb
    }
    deposit_events: store 0x00000000000000000000000000000001::Event::EventHandle<0x00000000000000000000000000000001::NFTGallery::DepositEvent<0x00000000000000000000000000000001::DAOExtensionPoint::OwnerNFTMeta>> {
        counter: 0
        guid: 0400000000000000a7dcef9aef26202fce82a7c7d6672afb
    }
    items: [
    ]
}

task 13 'run'. lines 91-110:
{
  "gas_used": 42895,
  "status": {
    "ExecutionFailure": {
      "location": {
        "Module": {
          "address": "0x00000000000000000000000000000001",
          "name": "DAOExtensionPoint"
        }
      },
      "function": 12,
      "code_offset": 10
    }
  }
}

task 14 'view'. lines 112-112:
[No Resource Exists]

task 15 'view'. lines 114-114:
[No Resource Exists]

task 16 'run'. lines 117-133:
{
  "gas_used": 39934,
  "status": {
    "MoveAbort": {
      "location": {
        "Module": {
          "address": "0x00000000000000000000000000000001",
          "name": "NFTGallery"
        }
      },
      "abort_code": "25861"
    }
  }
}
