processed 12 tasks

task 6 'run'. lines 32-40:
{
  "gas_used": 45401,
  "status": {
    "ExecutionFailure": {
      "location": {
        "Module": {
          "address": "0x00000000000000000000000000000001",
          "name": "DAOExtensionPoint"
        }
      },
      "function": 9,
      "code_offset": 22
    }
  }
}

task 7 'run'. lines 42-51:
{
  "gas_used": 23993,
  "status": {
    "ExecutionFailure": {
      "location": {
        "Module": {
          "address": "0x00000000000000000000000000000001",
          "name": "DAOExtensionPoint"
        }
      },
      "function": 10,
      "code_offset": 17
    }
  }
}

task 8 'run'. lines 53-62:
{
  "gas_used": 23993,
  "status": {
    "ExecutionFailure": {
      "location": {
        "Module": {
          "address": "0x00000000000000000000000000000001",
          "name": "DAOExtensionPoint"
        }
      },
      "function": 10,
      "code_offset": 17
    }
  }
}

task 9 'run'. lines 64-73:
{
  "gas_used": 23993,
  "status": {
    "ExecutionFailure": {
      "location": {
        "Module": {
          "address": "0x00000000000000000000000000000001",
          "name": "DAOExtensionPoint"
        }
      },
      "function": 10,
      "code_offset": 17
    }
  }
}

task 10 'view'. lines 75-75:
[No Resource Exists]

task 11 'view'. lines 77-77:
[No Resource Exists]
