processed 15 tasks

task 6 'run'. lines 47-55:
{
  "gas_used": 176645,
  "status": "Executed"
}

task 7 'run'. lines 57-65:
{
  "gas_used": 348165,
  "status": "Executed"
}

task 8 'run'. lines 67-78:
{
  "gas_used": 54001,
  "status": "Executed"
}

task 9 'run'. lines 80-91:
{
  "gas_used": 15374,
  "status": {
    "MoveAbort": {
      "location": {
        "Module": {
          "address": "0x00000000000000000000000000000001",
          "name": "DAOPluginMarketplace"
        }
      },
      "abort_code": "26881"
    }
  }
}

task 10 'run'. lines 93-104:
{
  "gas_used": 54001,
  "status": "Executed"
}

task 11 'view'. lines 106-106:
store key 0x00000000000000000000000000000001::DAOPluginMarketplace::PluginEntry<0x662ba5a1a1da0f1c70a9762c7eeb7aaf::TestPlugin::TestPlugin> {
    id: 1
    name: 54657374506c7567696e
    description: 697066733a2f2f6465736372697074696f6e
    labels: [
    ]
    next_version_number: 1
    versions: [
    ]
    star_count: 2
    created_at: 10000
    updated_at: 10000
}

task 12 'run'. lines 109-120:
{
  "gas_used": 44375,
  "status": "Executed"
}

task 13 'view'. lines 122-122:
store key 0x00000000000000000000000000000001::DAOPluginMarketplace::PluginEntry<0x662ba5a1a1da0f1c70a9762c7eeb7aaf::TestPlugin::TestPlugin> {
    id: 1
    name: 54657374506c7567696e
    description: 697066733a2f2f6465736372697074696f6e
    labels: [
    ]
    next_version_number: 1
    versions: [
    ]
    star_count: 1
    created_at: 10000
    updated_at: 10000
}

task 14 'run'. lines 124-135:
{
  "gas_used": 18574,
  "status": {
    "MoveAbort": {
      "location": {
        "Module": {
          "address": "0x00000000000000000000000000000001",
          "name": "DAOPluginMarketplace"
        }
      },
      "abort_code": "27137"
    }
  }
}
