processed 13 tasks

task 6 'run'. lines 31-39:
{
  "gas_used": 32113,
  "status": {
    "ExecutionFailure": {
      "location": {
        "Module": {
          "address": "0x00000000000000000000000000000001",
          "name": "DAOPluginMarketplace"
        }
      },
      "function": 12,
      "code_offset": 16
    }
  }
}

task 7 'run'. lines 41-49:
{
  "gas_used": 32113,
  "status": {
    "ExecutionFailure": {
      "location": {
        "Module": {
          "address": "0x00000000000000000000000000000001",
          "name": "DAOPluginMarketplace"
        }
      },
      "function": 12,
      "code_offset": 16
    }
  }
}

task 8 'run'. lines 51-59:
{
  "gas_used": 32113,
  "status": {
    "ExecutionFailure": {
      "location": {
        "Module": {
          "address": "0x00000000000000000000000000000001",
          "name": "DAOPluginMarketplace"
        }
      },
      "function": 12,
      "code_offset": 16
    }
  }
}

task 10 'run'. lines 87-95:
{
  "gas_used": 46029,
  "status": {
    "ExecutionFailure": {
      "location": {
        "Module": {
          "address": "0x00000000000000000000000000000001",
          "name": "DAOPluginMarketplace"
        }
      },
      "function": 12,
      "code_offset": 16
    }
  }
}

task 11 'view'. lines 97-97:
[No Resource Exists]

task 12 'run'. lines 99-107:
{
  "gas_used": 46029,
  "status": {
    "ExecutionFailure": {
      "location": {
        "Module": {
          "address": "0x00000000000000000000000000000001",
          "name": "DAOPluginMarketplace"
        }
      },
      "function": 12,
      "code_offset": 16
    }
  }
}
