processed 40 tasks

task 7 'run'. lines 123-132:
{
  "gas_used": 1275518,
  "status": {
    "MoveAbort": {
      "location": {
        "Module": {
          "address": "0x00000000000000000000000000000001",
          "name": "DAOSpace"
        }
      },
      "abort_code": "179201"
    }
  }
}

task 8 'run'. lines 136-150:
{
  "gas_used": 5286,
  "status": {
    "ExecutionFailure": {
      "location": {
        "Module": {
          "address": "0x00000000000000000000000000000001",
          "name": "DAORegistry"
        }
      },
      "function": 0,
      "code_offset": 1
    }
  }
}

task 9 'run'. lines 152-177:
{
  "gas_used": 306386,
  "status": "Executed"
}

task 11 'run'. lines 182-198:
{
  "gas_used": 42286,
  "status": {
    "ExecutionFailure": {
      "location": {
        "Module": {
          "address": "0x00000000000000000000000000000001",
          "name": "DAORegistry"
        }
      },
      "function": 0,
      "code_offset": 1
    }
  }
}

task 12 'run'. lines 200-216:
{
  "gas_used": 42286,
  "status": {
    "ExecutionFailure": {
      "location": {
        "Module": {
          "address": "0x00000000000000000000000000000001",
          "name": "DAORegistry"
        }
      },
      "function": 0,
      "code_offset": 1
    }
  }
}

task 16 'run'. lines 224-238:
{
  "gas_used": 104944,
  "status": "Executed"
}

task 19 'run'. lines 245-258:
{
  "gas_used": 532278,
  "status": {
    "MoveAbort": {
      "location": {
        "Module": {
          "address": "0x00000000000000000000000000000001",
          "name": "Block"
        }
      },
      "abort_code": "4609"
    }
  }
}

task 22 'run'. lines 265-276:
{
  "gas_used": 577624,
  "status": "Executed"
}

task 23 'run'. lines 279-303:
{
  "gas_used": 18867,
  "status": {
    "ExecutionFailure": {
      "location": {
        "Module": {
          "address": "0x00000000000000000000000000000001",
          "name": "DAORegistry"
        }
      },
      "function": 0,
      "code_offset": 1
    }
  }
}

task 25 'run'. lines 307-316:
{
  "gas_used": 11943,
  "status": "Executed"
}

task 26 'call'. lines 318-318:
"0xb5d577dc9ce59725e29886632e69ecdf/1/0x00000000000000000000000000000001::IdentifierNFT::IdentifierNFT<0x00000000000000000000000000000001::DAOSpace::DAOMember<0x662ba5a1a1da0f1c70a9762c7eeb7aaf::DAOHelper::X>,0x00000000000000000000000000000001::DAOSpace::DAOMemberBody<0x662ba5a1a1da0f1c70a9762c7eeb7aaf::DAOHelper::X>>"

task 28 'run'. lines 322-341:
{
  "gas_used": 3733,
  "status": {
    "ExecutionFailure": {
      "location": {
        "Module": {
          "address": "0x662ba5a1a1da0f1c70a9762c7eeb7aaf",
          "name": "DAOHelper"
        }
      },
      "function": 3,
      "code_offset": 1
    }
  }
}

task 29 'call'. lines 344-344:
"0xa7dcef9aef26202fce82a7c7d6672afb/1/0x00000000000000000000000000000001::IdentifierNFT::IdentifierNFT<0x00000000000000000000000000000001::DAOSpace::DAOMember<0x662ba5a1a1da0f1c70a9762c7eeb7aaf::DAOHelper::X>,0x00000000000000000000000000000001::DAOSpace::DAOMemberBody<0x662ba5a1a1da0f1c70a9762c7eeb7aaf::DAOHelper::X>>"

task 31 'run'. lines 348-361:
{
  "gas_used": 3205,
  "status": {
    "ExecutionFailure": {
      "location": {
        "Module": {
          "address": "0x662ba5a1a1da0f1c70a9762c7eeb7aaf",
          "name": "DAOHelper"
        }
      },
      "function": 3,
      "code_offset": 1
    }
  }
}

task 32 'call'. lines 364-364:
"0x3d4926eeda5b14b0ac979269ee79e40e/1/0x00000000000000000000000000000001::IdentifierNFT::IdentifierNFT<0x00000000000000000000000000000001::DAOSpace::DAOMember<0x662ba5a1a1da0f1c70a9762c7eeb7aaf::DAOHelper::X>,0x00000000000000000000000000000001::DAOSpace::DAOMemberBody<0x662ba5a1a1da0f1c70a9762c7eeb7aaf::DAOHelper::X>>"

task 34 'run'. lines 368-381:
{
  "gas_used": 3469,
  "status": {
    "ExecutionFailure": {
      "location": {
        "Module": {
          "address": "0x662ba5a1a1da0f1c70a9762c7eeb7aaf",
          "name": "DAOHelper"
        }
      },
      "function": 3,
      "code_offset": 1
    }
  }
}

task 36 'run'. lines 386-401:
{
  "gas_used": 2381,
  "status": {
    "ExecutionFailure": {
      "location": {
        "Module": {
          "address": "0x662ba5a1a1da0f1c70a9762c7eeb7aaf",
          "name": "DAOHelper"
        }
      },
      "function": 3,
      "code_offset": 1
    }
  }
}

task 39 'run'. lines 409-425:
{
  "gas_used": 17640,
  "status": {
    "ExecutionFailure": {
      "location": {
        "Module": {
          "address": "0x00000000000000000000000000000001",
          "name": "DAORegistry"
        }
      },
      "function": 0,
      "code_offset": 1
    }
  }
}
