processed 11 tasks

task 4 'run'. lines 9-17:
{
  "gas_used": 791553,
  "status": "Executed"
}

task 5 'view'. lines 19-19:
store key 0x00000000000000000000000000000001::DAOAccount::DAOAccountCap {
    dao_address: bf3a917cf4fb6425b95cc12763e6038b
}

task 7 'run'. lines 59-67:
{
  "gas_used": 79013,
  "status": "Executed"
}

task 10 'run'. lines 73-84:
{
  "gas_used": 1054663,
  "status": "Executed"
}
