processed 6 tasks

task 2 'run'. lines 6-23:
{
  "gas_used": 837509,
  "status": "Executed"
}

task 3 'run'. lines 28-40:
{
  "gas_used": 84519,
  "status": "Executed"
}

task 4 'run'. lines 42-51:
{
  "gas_used": 712879,
  "status": {
    "MoveAbort": {
      "location": {
        "Module": {
          "address": "0x00000000000000000000000000000001",
          "name": "DAOAccount"
        }
      },
      "abort_code": "25862"
    }
  }
}

task 5 'run'. lines 53-61:
{
  "gas_used": 711648,
  "status": {
    "MoveAbort": {
      "location": {
        "Module": {
          "address": "0x00000000000000000000000000000001",
          "name": "DAOAccount"
        }
      },
      "abort_code": "25862"
    }
  }
}
