processed 11 tasks

task 6 'run'. lines 46-54:
{
  "gas_used": 32113,
  "status": {
    "ExecutionFailure": {
      "location": {
        "Module": {
          "address": "0x00000000000000000000000000000001",
          "name": "DAOPluginMarketplace"
        }
      },
      "function": 12,
      "code_offset": 16
    }
  }
}

task 7 'view'. lines 56-56:
[No Resource Exists]

task 8 'run'. lines 58-66:
{
  "gas_used": 45883,
  "status": {
    "ExecutionFailure": {
      "location": {
        "Module": {
          "address": "0x00000000000000000000000000000001",
          "name": "DAOPluginMarketplace"
        }
      },
      "function": 16,
      "code_offset": 10
    }
  }
}

task 9 'run'. lines 68-76:
{
  "gas_used": 45883,
  "status": {
    "ExecutionFailure": {
      "location": {
        "Module": {
          "address": "0x00000000000000000000000000000001",
          "name": "DAOPluginMarketplace"
        }
      },
      "function": 16,
      "code_offset": 10
    }
  }
}

task 10 'view'. lines 78-78:
[No Resource Exists]
