processed 20 tasks

task 4 'run'. lines 86-94:
{
  "gas_used": 333211,
  "status": "Executed"
}

task 9 'run'. lines 116-131:
{
  "gas_used": 200239,
  "status": "Executed"
}

task 10 'run'. lines 133-142:
{
  "gas_used": 1155378,
  "status": "Executed"
}

task 12 'run'. lines 146-154:
{
  "gas_used": 140814,
  "status": "Executed"
}

task 15 'run'. lines 160-168:
{
  "gas_used": 11346,
  "status": "Executed"
}

task 16 'run'. lines 170-178:
{
  "gas_used": 140814,
  "status": "Executed"
}

task 18 'deploy'. lines 182-183:
Publish failure: MiscellaneousError

task 19 'run'. lines 185-193:
{
  "gas_used": 600,
  "status": "MiscellaneousError"
}
