processed 17 tasks

task 7 'run'. lines 134-143:
{
  "gas_used": 1171921,
  "status": "Executed"
}

task 8 'run'. lines 147-161:
{
  "gas_used": 0,
  "status": {
    "Discard": {
      "status_code": "506",
      "status_code_name": "SIGNER_ALREADY_DELEGATED"
    }
  }
}

task 9 'run'. lines 163-188:
{
  "gas_used": 306386,
  "status": "Executed"
}

task 10 'run'. lines 190-206:
{
  "gas_used": 235032,
  "status": "Executed"
}

task 11 'run'. lines 208-224:
{
  "gas_used": 235032,
  "status": "Executed"
}

task 12 'run'. lines 227-248:
{
  "gas_used": 240459,
  "status": {
    "MoveAbort": {
      "location": {
        "Module": {
          "address": "0x00000000000000000000000000000001",
          "name": "Block"
        }
      },
      "abort_code": "4609"
    }
  }
}

task 14 'run'. lines 252-298:
{
  "gas_used": 38453,
  "status": {
    "ExecutionFailure": {
      "location": {
        "Module": {
          "address": "0x00000000000000000000000000000001",
          "name": "DAOSpace"
        }
      },
      "function": 16,
      "code_offset": 8
    }
  }
}

task 16 'run'. lines 303-315:
{
  "gas_used": 46317,
  "status": {
    "ExecutionFailure": {
      "location": {
        "Module": {
          "address": "0x00000000000000000000000000000001",
          "name": "DAOSpace"
        }
      },
      "function": 70,
      "code_offset": 3
    }
  }
}
