processed 5 tasks

task 3 'view'. lines 7-7:
store key 0x00000000000000000000000000000001::DAOExtensionPoint::Registry {
    next_id: 1
}

task 4 'run'. lines 9-17:
{
  "gas_used": 13211,
  "status": {
    "MoveAbort": {
      "location": {
        "Module": {
          "address": "0x00000000000000000000000000000001",
          "name": "DAOExtensionPoint"
        }
      },
      "abort_code": "25606"
    }
  }
}
