processed 15 tasks

task 6 'run'. lines 44-52:
{
  "gas_used": 173740,
  "status": "Executed"
}

task 7 'run'. lines 54-62:
{
  "gas_used": 348165,
  "status": "Executed"
}

task 8 'run'. lines 64-75:
{
  "gas_used": 54001,
  "status": "Executed"
}

task 9 'run'. lines 77-88:
{
  "gas_used": 15374,
  "status": {
    "MoveAbort": {
      "location": {
        "Module": {
          "address": "0x00000000000000000000000000000001",
          "name": "DAOPluginMarketplace"
        }
      },
      "abort_code": "26881"
    }
  }
}

task 10 'run'. lines 90-101:
{
  "gas_used": 54001,
  "status": "Executed"
}

task 11 'view'. lines 103-103:
store key 0x00000000000000000000000000000001::DAOPluginMarketplace::PluginEntry<0x662ba5a1a1da0f1c70a9762c7eeb7aaf::TestPlugin::TestPlugin> {
    id: 1
    name: 54657374506c7567696e
    description: 697066733a2f2f6465736372697074696f6e
    labels: [
    ]
    next_version_number: 1
    versions: [
    ]
    star_count: 2
    created_at: 10000
    updated_at: 10000
}

task 12 'run'. lines 106-117:
{
  "gas_used": 44375,
  "status": "Executed"
}

task 13 'view'. lines 119-119:
store key 0x00000000000000000000000000000001::DAOPluginMarketplace::PluginEntry<0x662ba5a1a1da0f1c70a9762c7eeb7aaf::TestPlugin::TestPlugin> {
    id: 1
    name: 54657374506c7567696e
    description: 697066733a2f2f6465736372697074696f6e
    labels: [
    ]
    next_version_number: 1
    versions: [
    ]
    star_count: 1
    created_at: 10000
    updated_at: 10000
}

task 14 'run'. lines 121-132:
{
  "gas_used": 18574,
  "status": {
    "MoveAbort": {
      "location": {
        "Module": {
          "address": "0x00000000000000000000000000000001",
          "name": "DAOPluginMarketplace"
        }
      },
      "abort_code": "27137"
    }
  }
}
