processed 7 tasks

task 3 'run'. lines 54-61:
{
  "gas_used": 1031566,
  "status": {
    "MoveAbort": {
      "location": {
        "Module": {
          "address": "0x00000000000000000000000000000001",
          "name": "DAOSpace"
        }
      },
      "abort_code": "179201"
    }
  }
}

task 4 'view'. lines 63-63:
[No Resource Exists]

task 5 'view'. lines 65-65:
[No Resource Exists]

task 6 'view'. lines 67-67:
[No Resource Exists]
