processed 27 tasks

task 5 'run'. lines 67-75:
{
  "gas_used": 46617,
  "status": "Executed"
}

task 6 'run'. lines 77-85:
{
  "gas_used": 77620,
  "status": "Executed"
}

task 7 'run'. lines 87-96:
{
  "gas_used": 1259689,
  "status": "Executed"
}

task 9 'run'. lines 100-114:
{
  "gas_used": 614488,
  "status": "Executed"
}

task 13 'run'. lines 122-133:
{
  "gas_used": 101440,
  "status": "Executed"
}

task 16 'run'. lines 140-149:
{
  "gas_used": 575872,
  "status": "Executed"
}

task 17 'run'. lines 152-177:
{
  "gas_used": 471304,
  "status": "Executed"
}

task 19 'call'. lines 181-181:
"0xa7dcef9aef26202fce82a7c7d6672afb/1/0x00000000000000000000000000000001::IdentifierNFT::IdentifierNFT<0x00000000000000000000000000000001::DAOSpace::DAOMember<0x662ba5a1a1da0f1c70a9762c7eeb7aaf::XDAO::XDAO>,0x00000000000000000000000000000001::DAOSpace::DAOMemberBody<0x662ba5a1a1da0f1c70a9762c7eeb7aaf::XDAO::XDAO>>"

task 21 'run'. lines 185-200:
{
  "gas_used": 7794857,
  "status": "Executed"
}

task 23 'run'. lines 204-217:
{
  "gas_used": 173636,
  "status": "Executed"
}

task 24 'run'. lines 219-227:
{
  "gas_used": 48325,
  "status": "Executed"
}

task 26 'run'. lines 232-249:
{
  "gas_used": 583131,
  "status": "Executed"
}
