processed 29 tasks

task 8 'run'. lines 71-85:
{
  "gas_used": 125914,
  "status": "Executed"
}

task 9 'run'. lines 87-96:
{
  "gas_used": 1031566,
  "status": {
    "MoveAbort": {
      "location": {
        "Module": {
          "address": "0x00000000000000000000000000000001",
          "name": "DAOSpace"
        }
      },
      "abort_code": "179201"
    }
  }
}

task 10 'run'. lines 98-108:
{
  "gas_used": 25392,
  "status": {
    "ExecutionFailure": {
      "location": {
        "Module": {
          "address": "0x00000000000000000000000000000001",
          "name": "DAORegistry"
        }
      },
      "function": 0,
      "code_offset": 1
    }
  }
}

task 11 'run'. lines 110-123:
{
  "gas_used": 85910,
  "status": "Executed"
}

task 12 'run'. lines 125-139:
{
  "gas_used": 37244,
  "status": {
    "ExecutionFailure": {
      "location": {
        "Module": {
          "address": "0x00000000000000000000000000000001",
          "name": "DAORegistry"
        }
      },
      "function": 0,
      "code_offset": 1
    }
  }
}

task 16 'run'. lines 147-158:
{
  "gas_used": 101440,
  "status": "Executed"
}

task 19 'run'. lines 164-173:
{
  "gas_used": 575872,
  "status": "Executed"
}

task 20 'run'. lines 175-206:
{
  "gas_used": 19474,
  "status": {
    "ExecutionFailure": {
      "location": {
        "Module": {
          "address": "0x00000000000000000000000000000001",
          "name": "DAORegistry"
        }
      },
      "function": 0,
      "code_offset": 1
    }
  }
}

task 22 'call'. lines 210-210:
"0xa7dcef9aef26202fce82a7c7d6672afb/1/0x00000000000000000000000000000001::IdentifierNFT::IdentifierNFT<0x00000000000000000000000000000001::DAOSpace::DAOMember<0x662ba5a1a1da0f1c70a9762c7eeb7aaf::XDAO::XDAO>,0x00000000000000000000000000000001::DAOSpace::DAOMemberBody<0x662ba5a1a1da0f1c70a9762c7eeb7aaf::XDAO::XDAO>>"

task 24 'run'. lines 214-228:
{
  "gas_used": 33987,
  "status": {
    "MoveAbort": {
      "location": {
        "Module": {
          "address": "0x00000000000000000000000000000001",
          "name": "DAOSpace"
        }
      },
      "abort_code": "51201"
    }
  }
}

task 26 'run'. lines 232-246:
{
  "gas_used": 8850,
  "status": {
    "ExecutionFailure": {
      "location": {
        "Module": {
          "address": "0x00000000000000000000000000000001",
          "name": "DAORegistry"
        }
      },
      "function": 0,
      "code_offset": 1
    }
  }
}

task 28 'run'. lines 250-271:
{
  "gas_used": 8850,
  "status": {
    "ExecutionFailure": {
      "location": {
        "Module": {
          "address": "0x00000000000000000000000000000001",
          "name": "DAORegistry"
        }
      },
      "function": 0,
      "code_offset": 1
    }
  }
}
