processed 30 tasks

task 5 'run'. lines 11-18:
{
  "gas_used": 6344764,
  "status": "Executed"
}

task 9 'run'. lines 80-94:
{
  "gas_used": 125914,
  "status": "Executed"
}

task 10 'run'. lines 96-105:
{
  "gas_used": 1162585,
  "status": "Executed"
}

task 11 'run'. lines 107-117:
{
  "gas_used": 53739,
  "status": "Executed"
}

task 12 'run'. lines 119-132:
{
  "gas_used": 8525,
  "status": {
    "ExecutionFailure": {
      "location": {
        "Module": {
          "address": "0x00000000000000000000000000000001",
          "name": "Token"
        }
      },
      "function": 16,
      "code_offset": 2
    }
  }
}

task 13 'run'. lines 134-148:
{
  "gas_used": 264828,
  "status": "Executed"
}

task 17 'run'. lines 156-167:
{
  "gas_used": 101440,
  "status": "Executed"
}

task 20 'run'. lines 173-182:
{
  "gas_used": 575872,
  "status": "Executed"
}

task 21 'run'. lines 184-209:
{
  "gas_used": 435640,
  "status": "Executed"
}

task 23 'call'. lines 213-213:
"0xa7dcef9aef26202fce82a7c7d6672afb/1/0x00000000000000000000000000000001::IdentifierNFT::IdentifierNFT<0x00000000000000000000000000000001::DAOSpace::DAOMember<0x662ba5a1a1da0f1c70a9762c7eeb7aaf::XDAO::XDAO>,0x00000000000000000000000000000001::DAOSpace::DAOMemberBody<0x662ba5a1a1da0f1c70a9762c7eeb7aaf::XDAO::XDAO>>"

task 25 'run'. lines 217-231:
{
  "gas_used": 8799122,
  "status": "Executed"
}

task 27 'run'. lines 235-249:
{
  "gas_used": 172880,
  "status": "Executed"
}

task 29 'run'. lines 253-274:
{
  "gas_used": 513498,
  "status": "Executed"
}
