processed 29 tasks

task 8 'run'. lines 69-83:
{
  "gas_used": 125914,
  "status": "Executed"
}

task 9 'run'. lines 85-94:
{
  "gas_used": 1293341,
  "status": "Executed"
}

task 10 'run'. lines 96-106:
{
  "gas_used": 53739,
  "status": "Executed"
}

task 11 'run'. lines 108-121:
{
  "gas_used": 8525,
  "status": {
    "ExecutionFailure": {
      "location": {
        "Module": {
          "address": "0x00000000000000000000000000000001",
          "name": "Token"
        }
      },
      "function": 16,
      "code_offset": 2
    }
  }
}

task 12 'run'. lines 123-134:
{
  "gas_used": 616761,
  "status": "Executed"
}

task 16 'run'. lines 142-153:
{
  "gas_used": 101440,
  "status": "Executed"
}

task 19 'run'. lines 159-168:
{
  "gas_used": 575872,
  "status": "Executed"
}

task 20 'run'. lines 170-201:
{
  "gas_used": 486136,
  "status": "Executed"
}

task 22 'call'. lines 205-205:
"0xa7dcef9aef26202fce82a7c7d6672afb/1/0x00000000000000000000000000000001::IdentifierNFT::IdentifierNFT<0x00000000000000000000000000000001::DAOSpace::DAOMember<0x662ba5a1a1da0f1c70a9762c7eeb7aaf::XDAO::XDAO>,0x00000000000000000000000000000001::DAOSpace::DAOMemberBody<0x662ba5a1a1da0f1c70a9762c7eeb7aaf::XDAO::XDAO>>"

task 24 'run'. lines 209-223:
{
  "gas_used": 8799122,
  "status": "Executed"
}

task 26 'run'. lines 227-241:
{
  "gas_used": 173636,
  "status": "Executed"
}

task 28 'run'. lines 245-266:
{
  "gas_used": 550893,
  "status": "Executed"
}
