processed 11 tasks

task 2 'run'. lines 5-43:
{
  "gas_used": 68562,
  "status": "Executed"
}

task 3 'run'. lines 45-55:
{
  "gas_used": 23438,
  "status": {
    "MoveAbort": {
      "location": "Script",
      "abort_code": "102"
    }
  }
}

task 4 'run'. lines 57-90:
{
  "gas_used": 22527,
  "status": {
    "MoveAbort": {
      "location": {
        "Module": {
          "address": "0x00000000000000000000000000000001",
          "name": "ConsensusConfig"
        }
      },
      "abort_code": "4615"
    }
  }
}

task 5 'run'. lines 92-125:
{
  "gas_used": 22674,
  "status": {
    "MoveAbort": {
      "location": {
        "Module": {
          "address": "0x00000000000000000000000000000001",
          "name": "ConsensusConfig"
        }
      },
      "abort_code": "4615"
    }
  }
}

task 6 'run'. lines 127-160:
{
  "gas_used": 22634,
  "status": {
    "MoveAbort": {
      "location": {
        "Module": {
          "address": "0x00000000000000000000000000000001",
          "name": "ConsensusConfig"
        }
      },
      "abort_code": "4615"
    }
  }
}

task 7 'run'. lines 162-196:
{
  "gas_used": 22714,
  "status": {
    "MoveAbort": {
      "location": {
        "Module": {
          "address": "0x00000000000000000000000000000001",
          "name": "ConsensusConfig"
        }
      },
      "abort_code": "4615"
    }
  }
}

task 8 'run'. lines 198-232:
{
  "gas_used": 22754,
  "status": {
    "MoveAbort": {
      "location": {
        "Module": {
          "address": "0x00000000000000000000000000000001",
          "name": "ConsensusConfig"
        }
      },
      "abort_code": "4615"
    }
  }
}

task 9 'run'. lines 234-268:
{
  "gas_used": 22794,
  "status": {
    "MoveAbort": {
      "location": {
        "Module": {
          "address": "0x00000000000000000000000000000001",
          "name": "ConsensusConfig"
        }
      },
      "abort_code": "4615"
    }
  }
}

task 10 'run'. lines 270-304:
{
  "gas_used": 22594,
  "status": {
    "MoveAbort": {
      "location": {
        "Module": {
          "address": "0x00000000000000000000000000000001",
          "name": "ConsensusConfig"
        }
      },
      "abort_code": "4615"
    }
  }
}
