processed 10 tasks

task 5 'run'. lines 35-44:
{
  "gas_used": 24244,
  "status": "Executed"
}

task 6 'run'. lines 47-63:
{
  "gas_used": 43449,
  "status": {
    "MoveAbort": {
      "location": {
        "Module": {
          "address": "0x00000000000000000000000000000001",
          "name": "Collection2"
        }
      },
      "abort_code": "26114"
    }
  }
}

task 7 'run'. lines 66-79:
{
  "gas_used": 69071,
  "status": "Executed"
}

task 8 'run'. lines 82-95:
{
  "gas_used": 77854,
  "status": "Executed"
}

task 9 'run'. lines 98-111:
{
  "gas_used": 69502,
  "status": "Executed"
}
