processed 5 tasks

task 3 'run'. lines 7-17:
{
  "gas_used": 35687,
  "status": {
    "MoveAbort": {
      "location": {
        "Module": {
          "address": "0x00000000000000000000000000000001",
          "name": "Token"
        }
      },
      "abort_code": "25858"
    }
  }
}

task 4 'run'. lines 20-32:
{
  "gas_used": 37151,
  "status": {
    "MoveAbort": {
      "location": {
        "Module": {
          "address": "0x00000000000000000000000000000001",
          "name": "Token"
        }
      },
      "abort_code": "28161"
    }
  }
}
