processed 10 tasks

task 4 'run'. lines 91-99:
{
  "gas_used": 150838,
  "status": "Executed"
}

task 5 'run'. lines 101-113:
{
  "gas_used": 260316,
  "status": "Executed"
}

task 7 'run'. lines 118-130:
{
  "gas_used": 337814,
  "status": "Executed"
}

task 8 'run'. lines 132-152:
{
  "gas_used": 135024,
  "status": {
    "MoveAbort": {
      "location": "Script",
      "abort_code": "1002"
    }
  }
}

task 9 'run'. lines 155-180:
{
  "gas_used": 77055,
  "status": "Executed"
}
