processed 7 tasks

task 5 'run'. lines 14-20:
{
  "gas_used": 32320,
  "status": {
    "MoveAbort": {
      "location": {
        "Module": {
          "address": "0x00000000000000000000000000000001",
          "name": "CoreAddresses"
        }
      },
      "abort_code": "2818"
    }
  }
}

task 6 'run'. lines 22-34:
{
  "gas_used": 175859,
  "status": {
    "ExecutionFailure": {
      "location": {
        "Module": {
          "address": "0x00000000000000000000000000000001",
          "name": "EasyGas"
        }
      },
      "function": 2,
      "code_offset": 3
    }
  }
}
