name: 1. Build and Test
on:
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    name: build and test
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: checkout
        uses: actions/checkout@v1
        with:
          submodules: recursive
      - name: setup rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
      - name: setup environment
        run: |
          bash scripts/dev_setup.sh -b -t -y -p 
      - name: test
        run: |
          source "$HOME/.profile"
          mpm package test
      - name: spec test
        run: |
          source "$HOME/.profile"
          mpm spectest
      - name: move-prover-test
        run: |
          source "$HOME/.profile"
          mpm package prove
      # last run build for generate all abi and docs
      - name: build
        run: |
          source "$HOME/.profile"
          bash ./scripts/build.sh
      - name: check changed files
        run: bash ./scripts/changed_files.sh